#version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: orcamento-db
    environment:
      POSTGRES_DB: orcamento_db
      POSTGRES_USER: usuario_db
      POSTGRES_PASSWORD: senha_secreta_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: